parameters:
    crowd_reactive_lob.lob.class: Lob\Lob

services:
    crowd_reactive_lob.lob:
        class: %crowd_reactive_lob.lob.class%
        arguments:
            - %crowd_reactive_lob.api_key%
            - %crowd_reactive_lob.version%

